version: '3'

services:
  db:
    image: mongo
    restart: always

    #puesto del proyecto: puerto de salida del contenedor
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nest-pokemon
      # configurando el volumnet para no perder datos cada que cerremos el contenedor
    volumes:
      - ./mongo:/data/db
